spring.application.name=bankportal


spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bankportal
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=bankuser
spring.datasource.password=bankpassword

jwt.secret=your-very-long-random-secret-key-change-this-later-12345678
