spring.application.name=bankportal

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bankportal
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=bankuser
spring.datasource.password=bankpassword

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=your-very-long-random-secret-key-change-this-later-12345678

