name: Bank Portal CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: bankportal_test
          POSTGRES_USER: bankuser
          POSTGRES_PASSWORD: bankpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start Spring Boot
        working-directory: backend
        run: |
          mvn spring-boot:run &
          sleep 30
    
      - name: Install k6
        run: |
          sudo gpg -k
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: run stress tests
        working-directory: tests/k6
        run: k6 run stress-test.js
        